[package]
name = "aggressive_work_request"
version = "0.1.0"
authors = ["Baiqing_Lyu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
rev_lines = "0.2.1"
chrono = "0.4.11"
